//商品列表
let orderTabHead = [
    {
      fieldName: "商品ID",
      fieldChName: "商品ID",
      fieldEnName: "id",
      fieldNo: "id",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "商品名称",
      fieldChName: "商品名称",
      fieldEnName: "name",
      fieldNo: "name",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "购买数量",
      fieldChName: "购买数量",
      fieldEnName: "productNum",
      fieldNo: "productNum",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "单价",
      fieldChName: "单价",
      fieldEnName: "price",
      fieldNo: "price",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "总金额",
      fieldChName: "总金额",
      fieldEnName: "totalPrice",
      fieldNo: "totalPrice",
      fieldType: "input",
      width: 120,
    }, 
    {
      fieldName: "发货地址",
      fieldChName: "发货地址",
      fieldEnName: "receiveAddress",
      fieldNo: "receiveAddress",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "快递单号",
      fieldChName: "快递单号",
      fieldEnName: "logisticsNum",
      fieldNo: "logisticsNum",
      fieldType: "input",
      width: 120,
    },    
    {
      fieldName: "订单状态",
      fieldChName: "订单状态",
      fieldEnName: "state",
      fieldNo: "state",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "付款时间",
      fieldChName: "付款时间",
      fieldEnName: "state",
      fieldNo: "state",
      fieldType: "input",
      width: 120,
    },
  ]

export { orderTabHead };