//已预约
  let appointmentTabHead = [
    {
      fieldName: "订单编号",
      fieldChName: "订单编号",
      fieldEnName: "oderCode",
      fieldNo: "oderCode",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "预约时间",
      fieldChName: "预约时间",
      fieldEnName: "viewName",
      fieldNo: "viewName",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "场次",
      fieldChName: "场次",
      fieldEnName: "dataSource",
      fieldNo: "dataSource",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "价格",
      fieldChName: "价格",
      fieldEnName: "metaType",
      fieldNo: "metaType",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "数量",
      fieldChName: "数量",
      fieldEnName: "metaData",
      fieldNo: "metaData",
      fieldType: "input",
      width: 120,
    }, 
    {
      fieldName: "预约人姓名",
      fieldChName: "预约人姓名",
      fieldEnName: "metaDataTypeName",
      fieldNo: "metaDataTypeName",
      fieldType: "input",
      width: 120,
    },   
    {
      fieldName: "联系方式",
      fieldChName: "联系方式",
      fieldEnName: "allChecked",
      fieldNo: "allChecked",
      fieldType: "input",
      width: 120,
    },
  ]
//抢购中
 let specialOfferTabHead = [
    {
        fieldName: "订单编号",
        fieldChName: "订单编号",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
    {
        fieldName: "抢中时间",
        fieldChName: "抢中时间",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
    {
        fieldName: "抢中人",
        fieldChName: "抢中人",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
    {
        fieldName: "转卖人联系方式",
        fieldChName: "转卖人联系方式",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
    {
        fieldName: "场次",
        fieldChName: "场次",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },

    {
        fieldName: "价格",
        fieldChName: "价格",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
    {
        fieldName: "违约次数",
        fieldChName: "违约次数",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
    {
        fieldName: "流拍次数",
        fieldChName: "流拍次数",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
    {
        fieldName: "转卖人",
        fieldChName: "转卖人",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
    {
        fieldName: "可转卖倒计时",
        fieldChName: "可转卖倒计时",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
    {
        fieldName: "抢购状态",
        fieldChName: "抢购状态",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
    },
 ]
 //转卖中
 let resaleTabHead = [
    {
        fieldName: "订单编号",
        fieldChName: "订单编号",
        fieldEnName: "oderCode",
        fieldNo: "oderCode",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "抢中时间",
        fieldChName: "抢中时间",
        fieldEnName: "viewName",
        fieldNo: "viewName",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "转卖人",
        fieldChName: "转卖人",
        fieldEnName: "dataSource",
        fieldNo: "dataSource",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "转卖人联系方式",
        fieldChName: "转卖人联系方式",
        fieldEnName: "metaType",
        fieldNo: "metaType",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "场次",
        fieldChName: "场次",
        fieldEnName: "metaData",
        fieldNo: "metaData",
        fieldType: "input",
        width: 120,
      }, 
      {
        fieldName: "价格",
        fieldChName: "价格",
        fieldEnName: "metaDataTypeName",
        fieldNo: "metaDataTypeName",
        fieldType: "input",
        width: 120,
      },   
      {
        fieldName: "违约次数",
        fieldChName: "违约次数",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "流拍次数",
        fieldChName: "流拍次数",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "抢购状态",
        fieldChName: "抢购状态",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },
 ]

 //已违约
 let breakPromiseTabHead = [
    {
        fieldName: "订单编号",
        fieldChName: "订单编号",
        fieldEnName: "oderCode",
        fieldNo: "oderCode",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "抢中时间",
        fieldChName: "抢中时间",
        fieldEnName: "viewName",
        fieldNo: "viewName",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "抢中人",
        fieldChName: "抢中人",
        fieldEnName: "dataSource",
        fieldNo: "dataSource",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "场次",
        fieldChName: "场次",
        fieldEnName: "metaData",
        fieldNo: "metaData",
        fieldType: "input",
        width: 120,
      }, 
      {
        fieldName: "价格",
        fieldChName: "价格",
        fieldEnName: "metaDataTypeName",
        fieldNo: "metaDataTypeName",
        fieldType: "input",
        width: 120,
      },   
      {
        fieldName: "违约次数",
        fieldChName: "违约次数",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "流拍次数",
        fieldChName: "流拍次数",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "转卖人",
        fieldChName: "转卖人",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "转卖人联系方式",
        fieldChName: "转卖人联系方式",
        fieldEnName: "metaType",
        fieldNo: "metaType",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "抢购状态",
        fieldChName: "抢购状态",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },

 ]

 //已完成
 let finishTabHead = [
    {
        fieldName: "订单编号",
        fieldChName: "订单编号",
        fieldEnName: "oderCode",
        fieldNo: "oderCode",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "抢中时间",
        fieldChName: "抢中时间",
        fieldEnName: "viewName",
        fieldNo: "viewName",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "抢中人",
        fieldChName: "抢中人",
        fieldEnName: "dataSource",
        fieldNo: "dataSource",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "场次",
        fieldChName: "场次",
        fieldEnName: "metaData",
        fieldNo: "metaData",
        fieldType: "input",
        width: 120,
      }, 
      {
        fieldName: "价格",
        fieldChName: "价格",
        fieldEnName: "metaDataTypeName",
        fieldNo: "metaDataTypeName",
        fieldType: "input",
        width: 120,
      },   
      {
        fieldName: "违约次数",
        fieldChName: "违约次数",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "流拍次数",
        fieldChName: "流拍次数",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "转卖人",
        fieldChName: "转卖人",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "转卖人联系方式",
        fieldChName: "转卖人联系方式",
        fieldEnName: "metaType",
        fieldNo: "metaType",
        fieldType: "input",
        width: 120,
      },
      {
        fieldName: "抢购状态",
        fieldChName: "抢购状态",
        fieldEnName: "allChecked",
        fieldNo: "allChecked",
        fieldType: "input",
        width: 120,
      },

 ]

export { appointmentTabHead, specialOfferTabHead, resaleTabHead, breakPromiseTabHead, finishTabHead };