//商品列表
let memberTabHead = [
    {
      fieldName: "姓名",
      fieldChName: "姓名",
      fieldEnName: "oderCode",
      fieldNo: "oderCode",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "昵称",
      fieldChName: "昵称",
      fieldEnName: "viewName",
      fieldNo: "viewName",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "联系方式",
      fieldChName: "联系方式",
      fieldEnName: "dataSource",
      fieldNo: "dataSource",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "身份证号",
      fieldChName: "身份证号",
      fieldEnName: "metaType",
      fieldNo: "metaType",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "注册时间",
      fieldChName: "注册时间",
      fieldEnName: "metaData",
      fieldNo: "metaData",
      fieldType: "input",
      width: 120,
    }, 
    {
      fieldName: "微信",
      fieldChName: "微信",
      fieldEnName: "metaDataTypeName",
      fieldNo: "metaDataTypeName",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "支付宝",
      fieldChName: "支付宝",
      fieldEnName: "metaDataTypeName",
      fieldNo: "metaDataTypeName",
      fieldType: "input",
      width: 120,
    },    
    {
      fieldName: "银行卡",
      fieldChName: "银行卡",
      fieldEnName: "allChecked",
      fieldNo: "allChecked",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "已抢购金额",
      fieldChName: "已抢购金额",
      fieldEnName: "metaDataTypeName",
      fieldNo: "metaDataTypeName",
      fieldType: "input",
      width: 120,
    },    
    {
      fieldName: "会员等级",
      fieldChName: "会员等级",
      fieldEnName: "allChecked",
      fieldNo: "allChecked",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "账户状态",
      fieldChName: "账户状态",
      fieldEnName: "metaDataTypeName",
      fieldNo: "metaDataTypeName",
      fieldType: "input",
      width: 120,
    },    
    {
      fieldName: "猫豆余额",
      fieldChName: "猫豆余额",
      fieldEnName: "allChecked",
      fieldNo: "allChecked",
      fieldType: "input",
      width: 120,
    },
  ]

export { memberTabHead };