//商品列表
let memberTabHead = [
    {
      fieldName: "姓名",
      fieldChName: "姓名",
      fieldEnName: "name",
      fieldNo: "name",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "昵称",
      fieldChName: "昵称",
      fieldEnName: "nickName",
      fieldNo: "nickName",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "联系方式",
      fieldChName: "联系方式",
      fieldEnName: "phone",
      fieldNo: "phone",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "身份证号",
      fieldChName: "身份证号",
      fieldEnName: "idNo",
      fieldNo: "idNo",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "注册时间",
      fieldChName: "注册时间",
      fieldEnName: "createTime",
      fieldNo: "createTime",
      fieldType: "input",
      width: 120,
    }, 
    {
      fieldName: "微信",
      fieldChName: "微信",
      fieldEnName: "wechatNo",
      fieldNo: "wechatNo",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "支付宝",
      fieldChName: "支付宝",
      fieldEnName: "alipayNo",
      fieldNo: "alipayNo",
      fieldType: "input",
      width: 120,
    },    
    {
      fieldName: "银行卡",
      fieldChName: "银行卡",
      fieldEnName: "bank",
      fieldNo: "bank",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "已抢购金额",
      fieldChName: "已抢购金额",
      fieldEnName: "buyReword",
      fieldNo: "buyReword",
      fieldType: "input",
      width: 120,
    },    
    {
      fieldName: "会员等级",
      fieldChName: "会员等级",
      fieldEnName: "allChecked",
      fieldNo: "allChecked",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "账户状态",
      fieldChName: "账户状态",
      fieldEnName: "state",
      fieldNo: "state",
      fieldType: "input",
      width: 120,
    },    
    {
      fieldName: "猫豆余额",
      fieldChName: "猫豆余额",
      fieldEnName: "catFood",
      fieldNo: "catFood",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "奖励金",
      fieldChName: "奖励金",
      fieldEnName: "buyReword",
      fieldNo: "buyReword",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "分享值",
      fieldChName: "分享值",
      fieldEnName: "teamReward",
      fieldNo: "teamReward",
      fieldType: "input",
      width: 120,
    },
    {
      fieldName: "分润",
      fieldChName: "分润",
      fieldEnName: "childReward",
      fieldNo: "childReward",
      fieldType: "input",
      width: 120,
    },
  ]

export { memberTabHead };